# 参考 https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_toc.html
all: 

print-default-var:
	# make 隐含变量 参考 https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
	# 默认 C 编译器 
	echo $(CC)
	# 默认汇编器
	echo $(AS)
	# 默认 C++ 编译器
	echo $(CXX)
	# 默认 C 预处理器
	echo $(CPP)

implicit rule:
	# 隐含规则,把对应的 .c 文件编译为对应的目标文件
	

static-pattern:
